services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    # Pour la prod, décommente la ligne suivante
    # command: npm start  
    # Pour le dev avec hot reload, décommente:
    # command: npm run dev  

  nginx:
    build: ./frontend/
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

